### ISSUE TITLE
Persistent error message

### ISSUE THREAD

**Issue by mittkonto** [kochd/electricsheep-hd-client#50] opened 2020-02-11 11:01 UTC
I get this error and cant get rid of it:

`Downloading electricsheep.244.02218.03861_electricsheep.244.02218.03861 ...
Traceback (most recent call last):
		10: from daemon:342:in `<main>'
		 9: from daemon:342:in `loop'
		 8: from daemon:383:in `block in <main>'
		 7: from daemon:198:in `request_work'
		 6: from daemon:233:in `download_animated_genome'
		 5: from daemon:233:in `open'
		 4: from daemon:234:in `block in download_animated_genome'
		 3: from daemon:234:in `open'
		 2: from daemon:235:in `block (2 levels) in download_animated_genome'
		 1: from daemon:235:in `copy_stream'
daemon:235:in `readpartial': invalid code lengths set (Zlib::DataError)`

I restart the GPU daemon

`C:/Program Files (x86)/Electric Sheep HD/branches/G244_W3840_H2160_Q1024_KY38402AGPU/animated_genomes/electricsheep.244.02218.03861_electricsheep.244.02218.03861.flame:98530: parser error : Opening and ending tag mismatch: sequence line 1 and edit
   </edit>
		  ^
C:/Program Files (x86)/Electric Sheep HD/branches/G244_W3840_H2160_Q1024_KY38402AGPU/animated_genomes/electricsheep.244.02218.03861_electricsheep.244.02218.03861.flame:98531: parser error : Extra content at the end of the document
<
^
C:/Program Files (x86)/Electric Sheep HD/branches/G244_W3840_H2160_Q1024_KY38402AGPU/animated_genomes/electricsheep.244.02218.03861_electricsheep.244.02218.03861.flame:1: parser error : Start tag expected, '<' not found
þî╝þàÑµòÁµì«ÔüÑµòÂþì▓µ¢®ÒÁ«õÿóõàîÒììõ░¡ÕíÄÒî¡ÒÇ«Òä«Ôê«Ó¿¥µÿ╝µà¼µò¡þÿáþëÑµÑ│µ╣»Ôê
^
Error parsing flame file C:/Program Files (x86)/Electric Sheep HD/branches/G244_W3840_H2160_Q1024_KY38402AGPU/animated_genomes/electricsheep.244.02218.03861_electricsheep.244.02218.03861.flame, returning without executing.
Traceback (most recent call last):
		4: from daemon:342:in `<main>'
		3: from daemon:342:in `loop'
		2: from daemon:383:in `block in <main>'
		1: from daemon:201:in `request_work'
daemon:268:in `ember_render_frame': Emberrender exited: 1 (RuntimeError)
Press any key to continue . . .`

How do I get churning away frames again?
Using latest release.

**Comment by kochd** [comment] 2020-02-11 16:22
Hello @mittkonto thank you for reporting this. This was caused by a broken flame file on server side.
Its fixed now.

**Closed by kochd** 2020-02-11 16:22 UTC
