### ISSUE TITLE
Fractorium hangs at "Stage = iterating, progress = 100%, eta = 0.00s"

### ISSUE THREAD

**Issue by rggassner** [kochd/electricsheep-hd-client#55] opened 2020-08-14 21:04 UTC
Hi,

I'm beeing able to run fine on CPU, but when i try to run on GPU nothing happens.

Fractorium 1.0.0.20 is installed and working with gpu (i'm not sure if it is a dependency)

Any advice?

```
C:\Program Files (x86)\Electric Sheep HD>daemon_windows.cmd --gpu-list-devices

C:\Program Files (x86)\Electric Sheep HD>title Electric Sheep HD daemon

C:\Program Files (x86)\Electric Sheep HD>CD /D C:\Program Files (x86)\Electric Sheep HD\

C:\Program Files (x86)\Electric Sheep HD>SET PATH=C:\WINDOWS\system32;C:\Program Files (x86)\Electric Sheep HD\contrib\bin

C:\Program Files (x86)\Electric Sheep HD>ruby daemon --gpu-list-devices   || pause

OpenCL Info:
Platform 0: NVIDIA Corporation NVIDIA CUDA OpenCL 1.2 CUDA 11.0.208
Device 0: NVIDIA Corporation GeForce RTX 2060
CL_DEVICE_OPENCL_C_VERSION: OpenCL C 1.2
CL_DEVICE_LOCAL_MEM_SIZE: 49,152
CL_DEVICE_LOCAL_MEM_TYPE: 1
CL_DEVICE_MAX_COMPUTE_UNITS: 30
CL_DEVICE_MAX_READ_IMAGE_ARGS: 256
CL_DEVICE_MAX_WRITE_IMAGE_ARGS: 32
CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1,610,612,736
CL_DEVICE_ADDRESS_BITS: 64
CL_DEVICE_GLOBAL_MEM_CACHE_TYPE: 2
CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE: 128
CL_DEVICE_GLOBAL_MEM_CACHE_SIZE: 983,040
CL_DEVICE_GLOBAL_MEM_SIZE: 6,442,450,944
CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE: 65,536
CL_DEVICE_MAX_CONSTANT_ARGS: 9
CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS: 3
CL_DEVICE_MAX_WORK_GROUP_SIZE: 1,024
CL_DEVICE_MAX_WORK_ITEM_SIZES: 1,024, 1,024, 64



C:\Program Files (x86)\Electric Sheep HD>daemon_windows.cmd --gpu

C:\Program Files (x86)\Electric Sheep HD>title Electric Sheep HD daemon

C:\Program Files (x86)\Electric Sheep HD>CD /D C:\Program Files (x86)\Electric Sheep HD\

C:\Program Files (x86)\Electric Sheep HD>SET PATH=C:\WINDOWS\system32;C:\Program Files (x86)\Electric Sheep HD\contrib\bin

C:\Program Files (x86)\Electric Sheep HD>ruby daemon --gpu   || pause
[17:53:17] INFO: Active season: G244_W3840_H2160_Q1024_KFVGM5cUGPU
[17:53:17] INFO: Cleaning up animated genomes...
[17:53:17] INFO: Hashing files for p2p announce
[17:53:17] INFO: Updating DHT
[17:53:18] INFO: Requesting new sequence ...
[17:53:20] WARN: Server response 950: Not enough credits. Render 38 more frames.
[17:53:20] INFO: Not enough credits. Render 38 more frames.
[17:53:20] INFO: Requesting new work...
[17:53:20] INFO: Solving PoW...
[17:53:35] INFO: Solved after 15 seconds
[17:53:40] INFO: Downloading electricsheep.244.00619.12967_electricsheep.244.00619.12967 ...
[17:53:44] INFO: Rendering... electricsheep.244.00619.12967_electricsheep.244.00619.12967 Frame 116-120
Using OpenCL to render.
Parsing ember file C:/Program Files (x86)/Electric Sheep HD/branches/G244_W3840_H2160_Q1024_KFVGM5cUGPU/animated_genomes/electricsheep.244.00619.12967_electricsheep.244.00619.12967.flame
Finished parsing.
Stage = iterating, progress = 100%, eta = 0.00s


```

**Comment by kochd** [comment] 2020-08-16 01:17
So?
Looks good to me... or does it stop @"Stage = iterating, progress = 100%, eta = 0.00s" ?

**Comment by kochd** [comment] 2020-08-16 01:24
Somebody reported this before but either never figured out whats wrong or did not reply: https://github.com/kochd/electricsheep-hd-client/issues/40

If this is the case then this problem is related to Nvidia & Fractorium and not to Electric Sheep HD. Sorry about that.

**Comment by rggassner** [comment] 2020-08-16 02:34
> Somebody reported this before but either never figured out whats wrong or did not reply: #40
> 
> If this is the case then this problem is related to Nvidia & Fractorium and not to Electric Sheep HD. Sorry about that.

The same is happening here. It gets stuck at 100%,  but EmberAnimate.exe keeps using high GPU resources.
If i kill the process i get

```
Stage = iterating, progress = 100%, eta = 0.00sException `RuntimeError' at daemon:276 - Emberrender exited: 1
Traceback (most recent call last):
        4: from daemon:353:in `<main>'
        3: from daemon:353:in `loop'
        2: from daemon:397:in `block in <main>'
        1: from daemon:209:in `request_work'
daemon:276:in `ember_render_frame': Emberrender exited: 1 (RuntimeError)
Press any key to continue . . .

```

Is there a way i can run AmberAnimate.exe with the same parameters electricsheep is passing, in order to test it?

By the way, nicely done, im loving this full hd electricsheep!

**Comment by kochd** [comment] 2020-08-16 02:55
https://github.com/kochd/electricsheep-hd-client/blob/master/daemon#L262

**Comment by kochd** [comment] 2020-08-16 02:57
```
%APPDATA%\Fractorium\emberanimate --in "C:\Program Files (x86)\Electric Sheep HD\branches\G244_W3840_H2160_Q1024_KFVGM5cUGPU\animated_genomes\electricsheep.244.00619.12967_electricsheep.244.00619.12967.flame" --format=jpeg --opencl --sp --isaac_seed=fractorium
```

**Comment by rggassner** [comment] 2020-08-16 05:11
Thanks, that helped a lot. I was able to make it work with the parameter --supersample=2, other values don´t work. Also, format must be jpg, since there is no jpeg, and a png is generated instead.

If I manually add this parameter to the daemon, will the generated files still be compatible?

```
C:\Program Files (x86)\Electric Sheep HD>%APPDATA%\Fractorium\emberanimate --in "C:\Program Files (x86)\Electric Sheep HD\branches\G244_W3840_H2160_Q1024_KFVGM5cUGPU\animated_genomes\electricsheep.244.00619.12967_electricsheep.244.00619.12967.flame" --format=jpg --opencl --sp --isaac_seed=fractorium --verbose --progress --supersample=2
Using single precision.
Using OpenCL to render.
Platform: NVIDIA Corporation NVIDIA CUDA OpenCL 1.2 CUDA 11.0.208
Device: NVIDIA Corporation GeForce RTX 2060
Parsing ember file C:\Program Files (x86)\Electric Sheep HD\branches\G244_W3840_H2160_Q1024_KFVGM5cUGPU\animated_genomes\electricsheep.244.00619.12967_electricsheep.244.00619.12967.flame
Finished parsing.
Time = 1 / 1,800 / 1
Stage = iterating, progress = 100%, eta = 0.00s
Stage = filtering, progress = 100%, eta = 0.00s
Iters ran/requested: 8,493,465,600 / 8,493,465,600 (100.00%)
Render time: 12.42s
Pure iter time: 11.97s
Iters/sec: 709,313,771
Time = 2 / 1,800 / 1
Writing C:\Program Files (x86)\Electric Sheep HD\branches\G244_W3840_H2160_Q1024_KFVGM5cUGPU\animated_genomes\0000.jpg

Stage = iterating, progress = 100%, eta = 0.00s
Stage = filtering, progress = 100%, eta = 0.00s
Iters ran/requested: 8,493,465,600 / 8,493,465,600 (100.00%)
Render time: 12.38s
Pure iter time: 11.98s
Iters/sec: 708,946,249
Time = 3 / 1,800 / 1
Writing C:\Program Files (x86)\Electric Sheep HD\branches\G244_W3840_H2160_Q1024_KFVGM5cUGPU\animated_genomes\0001.jpg
```


Thanks a lot

**Comment by kochd** [comment] 2020-08-16 06:28
> If I manually add this parameter (--supersample=2) to the daemon, will the generated files still be compatible?

No its not compatible. As it differs visually. 
Are you sure it is related to supersampling? This makes absolutely no sense to me as supersampling adds complexity to the rendering process.

**Comment by kochd** [comment] 2020-08-16 06:41
Every flame is rendered @ supersample="1"

**Comment by kochd** [comment] 2020-08-16 06:54
If this is really reproducible by altering the supersample parameter you may want to report it as a bug [here](https://bitbucket.org/mfeemster/fractorium/issues)

**Comment by rggassner** [comment] 2020-08-16 07:46
Thank you for the help. It is reproducible.
Bug reported:
https://bitbucket.org/mfeemster/fractorium/issues/36/problem-with-supersample-1-command-line

**Comment by kochd** [comment] 2020-08-25 05:09
I am closing this for now as the [issue](https://bitbucket.org/mfeemster/fractorium/issues/36/problem-with-supersample-1-command-line) on the fractorium repository is making progress

**Comment by rggassner** [comment] 2020-09-02 23:05
Hi @kochd , 
I´m still trying to arrange a simillar hardware to see if the issue is reproducible on other systems. 
Would you kindly consider using SuperSample 2 in future seasons? 
If you could please read the fractorium bug report, Matt did some interesting considerations on the subject.

Thank you again,

**Comment by kochd** [comment] 2020-09-03 05:21
Okay. I hoped that an actual fix to this bug would be found. Lets fix it they dirty way:

New animated_genomes will be generated with supersample=2 now.
This should be stable in use in about 72 hours as you are randomly requested to validate frames from the past 48 hours which might be still generated with supersample=1 as parameter.

I am sure someday nvidia will produce cards which consistendly fail on supersample=2 (if they aren't around yet). They dont seam to get their opencl stuff right constantly.

**Comment by kochd** [comment] 2020-09-04 09:04
I can confirm that the job creation is working as intended (using supersample=2).

**Comment by ecexcursion** [comment] 2020-09-08 04:53
I just want to report that I was having the exact same issue as rggassner - and now it seems to be fixed. (I also have the same Nvidia GPU if that matters)

**Comment by kochd** [comment] 2020-09-08 05:24
Thank you. I am closing this then. Glad it's fixed.

**Closed by kochd** 2020-09-08 05:24 UTC
Labels: gpu, windows
