### ISSUE TITLE
Error uploading GPU renders

### ISSUE THREAD

**Issue by McLovinI87** [kochd/electricsheep-hd-client#70] opened 2021-03-01 12:32 UTC
I can upload my cpu renders fine but with the gpu renders i get this error when uploading

Error in upload: DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN
html head
title 502 Bad Gateway /title
/head body
h1 Bad Gateway /h1
 p The proxy server received an invalid
response from an upstream server. br /
/p
hr
address>Apache/2.4.25 (Debian) Server at sheeps.triple6.org Port 443 /address
/body /html

**Comment by kochd** [comment] 2021-03-01 12:54
Are you sure this is reproduce able?
I suspect this to be a load issue on server side where your upload fails because it takes too long to get through the proxy or you don't get a connection to one of the downstream servers. at least this is what i see on the server.

The reason for this is that we use low budget servers for high bandwidth operations.

**Comment by McLovinI87** [comment] 2021-03-01 13:37
Could be my upload speed. Ill test on some different internet when i can. would this be a server side timeout or a client side timeout that i can adjust?

**Comment by kochd** [comment] 2021-03-01 14:02
The timeout is raised by the server not the client.
The downloads of 4k movie files will be even worse for you then.

**Comment by McLovinI87** [comment] 2021-03-01 20:30
Update: It is definatly my upload speed thats the problem. with a better upload speed today i was able to upload some gpu renders.

Download speeds are good, about 8-12Mbps but upload is slow and varies between 200Kbps-1Mbps.

**Comment by kochd** [comment] 2021-03-02 06:55
Okay. I am closing this then.

**Closed by kochd** 2021-03-02 06:55 UTC
